---
- hosts: listofhosts
  vars:
  - warName: helloworld.war
  - warRemotePath: ~/

  tasks:
  - name: Download WAR to server
    synchronize: src={{ ~/ }}/{{ helloworld.war }} dest={{ ~/ }}/{{ helloworld.war }}

  - name: Unzip WAR file
    unarchive: src={{ ~/ }}/{{ helloworld.war }} dest=/var/lib/tomcat7/webapps/ROOT/ copy=no mode=0755 owner=tomcat7 group=tomcat7
    notify:
        - Restart tomcat7

  - name: Delete remote war file
    file: path={{ ~/ }}/{{ helloworld.war }} state=absent

  handlers:
    - name: Restart tomcat7
      service: name=tomcat7 state=restarted
